server:
  port: 9082



spring:
  application:
    name: user-communication
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0

logging:
  level:
    com.netflix.eureka: debug
    com.netflix.discovery: debug
    org.springframework.security: debug
    org:
      springframework:
        cloud:
          openfeign: debug


