version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data

  chat-auth:
    container_name: chat-auth
    image: .
volumes:
  my-db:
